[General]
dns-server = 223.5.5.5

[Proxy]
🇭🇰 日用 专线 香港 [0.2] = ss, 29592fdc743801.11992169.xyz, 14091, encrypt-method=chacha20-ietf-poly1305, password=lE9uL5fR3yR9,obfs=http,obfs-host=5ae41c5231.iqiyi.com, tfo=false, udp-relay=true
手动节点 = ss, 你的服务器IP, 你的端口, encrypt-method=chacha20-ietf-poly1305, password=你的密码

[Proxy Group]
Proxies =🇭🇰 日用 专线 香港 [0.2]
SelectGroup = select, 手动节点, DIRECT

[Rule]
FINAL, SelectGroup
